package view;

import controller.IncidentController;
import model.Incident;

import javax.swing.*;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public class IncidentDialog extends JDialog {

    private JTextField idField, titleField, assignedToField;
    private JTextArea descriptionArea, resolutionArea;
    private JComboBox<Incident.IncidentType> typeBox;
    private JComboBox<Incident.Risk> riskBox;
    private JComboBox<Incident.Status> statusBox;
    private JFormattedTextField dateField;

    private IncidentController controller;
    private Incident incident; // null for add, not null for update

    public IncidentDialog(JFrame parent, IncidentController controller, Incident incident) {
        super(parent, true);
        this.controller = controller;
        this.incident = incident;

        setTitle(incident == null ? "Add Incident" : "Update Incident");
        setSize(500, 600);
        setLocationRelativeTo(parent);

        initUI();
        if (incident != null) loadIncidentData();
        else {
            // For new incidents, ID is generated by the DB
            idField.setText("(auto-generated)");
            idField.setEditable(false);
            idField.setEnabled(false);
        }
    }

    private void initUI() {
        JPanel panel = new JPanel(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();
        c.fill = GridBagConstraints.HORIZONTAL;

        idField = new JTextField();
        titleField = new JTextField();
        descriptionArea = new JTextArea(3, 20);
        resolutionArea = new JTextArea(3, 20);
        assignedToField = new JTextField();

        typeBox = new JComboBox<>(Incident.IncidentType.values());
        riskBox = new JComboBox<>(Incident.Risk.values());
        statusBox = new JComboBox<>(Incident.Status.values());

        dateField = new JFormattedTextField(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"));
        dateField.setValue(new Date());

        JButton saveBtn = new JButton("Save");
        saveBtn.addActionListener(e -> saveIncident());

        int y = 0;

        panel.add(new JLabel("Incident ID:"), c); c.gridy = y; panel.add(idField, c); y++;
        panel.add(new JLabel("Title:"), c); c.gridy = y; panel.add(titleField, c); y++;
        panel.add(new JLabel("Description:"), c); c.gridy = y; panel.add(new JScrollPane(descriptionArea), c); y++;
        panel.add(new JLabel("Type:"), c); c.gridy = y; panel.add(typeBox, c); y++;
        panel.add(new JLabel("Risk:"), c); c.gridy = y; panel.add(riskBox, c); y++;
        panel.add(new JLabel("Status:"), c); c.gridy = y; panel.add(statusBox, c); y++;
        panel.add(new JLabel("Reported Date:"), c); c.gridy = y; panel.add(dateField, c); y++;
        panel.add(new JLabel("Assigned To:"), c); c.gridy = y; panel.add(assignedToField, c); y++;
        panel.add(new JLabel("Resolution Notes:"), c); c.gridy = y; panel.add(new JScrollPane(resolutionArea), c); y++;
        panel.add(saveBtn, c);

        add(panel);
    }

    private void loadIncidentData() {
        idField.setText(incident.getIncidentId() == null ? "" : incident.getIncidentId().toString());
        idField.setEditable(false);
        titleField.setText(incident.getTitle());
        descriptionArea.setText(incident.getDescription());
        typeBox.setSelectedItem(incident.getType());
        riskBox.setSelectedItem(incident.getRisk());
        statusBox.setSelectedItem(incident.getStatus());
        dateField.setValue(incident.getReportedDate());
        assignedToField.setText(incident.getAssignedTo());
        resolutionArea.setText(incident.getResolutionNotes());
    }

    private void saveIncident() {
        String title = titleField.getText().trim();
        String description = descriptionArea.getText().trim();
        Incident.IncidentType type = (Incident.IncidentType) typeBox.getSelectedItem();
        Incident.Risk risk = (Incident.Risk) riskBox.getSelectedItem();
        Incident.Status status = (Incident.Status) statusBox.getSelectedItem();
        Date reportedDate = (Date) dateField.getValue();
        String assignedTo = assignedToField.getText().trim();
        String resolutionNotes = resolutionArea.getText().trim();

        try {
            if (incident == null) {
                controller.addIncident(title, description, type, risk, status, reportedDate, assignedTo, resolutionNotes);
            } else {
                incident.setTitle(title);
                incident.setDescription(description);
                incident.setType(type);
                incident.setRisk(risk);
                incident.setStatus(status);
                incident.setReportedDate(reportedDate);
                incident.setAssignedTo(assignedTo);
                incident.setResolutionNotes(resolutionNotes);
                controller.updateIncident(incident);
            }
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }
}
